# Generated by Django 3.0.5 on 2020-04-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rollno',
            field=models.CharField(max_length=10),
        ),
    ]
